// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVfpvbZBmXByCArmgjI7GkLIjL0lzJ3D0',
    appId: '1:927626021690:web:26487c00f2e10717ae9e03',
    messagingSenderId: '927626021690',
    projectId: 'cybrosys-de66e',
    authDomain: 'cybrosys-de66e.firebaseapp.com',
    storageBucket: 'cybrosys-de66e.firebasestorage.app',
    measurementId: 'G-FDCQ5EVX55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtuw2m87sYsqvVAH2kAG0goH-LQ21rMvA',
    appId: '1:927626021690:android:264e90bb550a22e5ae9e03',
    messagingSenderId: '927626021690',
    projectId: 'cybrosys-de66e',
    storageBucket: 'cybrosys-de66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-KQDF6wpInZ-fvt_oRTYpURV6snp3FwE',
    appId: '1:927626021690:ios:8bb5d2c2ee7ccb38ae9e03',
    messagingSenderId: '927626021690',
    projectId: 'cybrosys-de66e',
    storageBucket: 'cybrosys-de66e.firebasestorage.app',
    iosBundleId: 'com.cybrosis.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-KQDF6wpInZ-fvt_oRTYpURV6snp3FwE',
    appId: '1:927626021690:ios:8bb5d2c2ee7ccb38ae9e03',
    messagingSenderId: '927626021690',
    projectId: 'cybrosys-de66e',
    storageBucket: 'cybrosys-de66e.firebasestorage.app',
    iosBundleId: 'com.cybrosis.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVfpvbZBmXByCArmgjI7GkLIjL0lzJ3D0',
    appId: '1:927626021690:web:a98229e08d5487e9ae9e03',
    messagingSenderId: '927626021690',
    projectId: 'cybrosys-de66e',
    authDomain: 'cybrosys-de66e.firebaseapp.com',
    storageBucket: 'cybrosys-de66e.firebasestorage.app',
    measurementId: 'G-GFRN1VCB6S',
  );

}